// 世界の国・地域別人口（2024年 推計 / 単位: 千人）
// 出典ベース: United Nations World Population Prospects 2024 revision の中位推計
// n=国名(日本語), e=英語名, c=ISO 3166-1 alpha-2, r=地域, p=人口(千人)
const COUNTRIES = [
  { n: "インド", e: "India", c: "IN", r: "アジア", p: 1450936 },
  { n: "中国", e: "China", c: "CN", r: "アジア", p: 1419321 },
  { n: "アメリカ合衆国", e: "United States", c: "US", r: "北米", p: 345427 },
  { n: "インドネシア", e: "Indonesia", c: "ID", r: "アジア", p: 283488 },
  { n: "パキスタン", e: "Pakistan", c: "PK", r: "アジア", p: 251269 },
  { n: "ナイジェリア", e: "Nigeria", c: "NG", r: "アフリカ", p: 232679 },
  { n: "ブラジル", e: "Brazil", c: "BR", r: "南米", p: 211999 },
  { n: "バングラデシュ", e: "Bangladesh", c: "BD", r: "アジア", p: 173562 },
  { n: "ロシア", e: "Russia", c: "RU", r: "ヨーロッパ", p: 144820 },
  { n: "エチオピア", e: "Ethiopia", c: "ET", r: "アフリカ", p: 132060 },
  { n: "メキシコ", e: "Mexico", c: "MX", r: "北米", p: 130861 },
  { n: "日本", e: "Japan", c: "JP", r: "アジア", p: 123753 },
  { n: "エジプト", e: "Egypt", c: "EG", r: "アフリカ", p: 116538 },
  { n: "フィリピン", e: "Philippines", c: "PH", r: "アジア", p: 115843 },
  { n: "コンゴ民主共和国", e: "DR Congo", c: "CD", r: "アフリカ", p: 109276 },
  { n: "ベトナム", e: "Vietnam", c: "VN", r: "アジア", p: 100987 },
  { n: "イラン", e: "Iran", c: "IR", r: "アジア", p: 91567 },
  { n: "トルコ", e: "Turkey", c: "TR", r: "アジア", p: 87473 },
  { n: "ドイツ", e: "Germany", c: "DE", r: "ヨーロッパ", p: 84552 },
  { n: "タイ", e: "Thailand", c: "TH", r: "アジア", p: 71669 },
  { n: "イギリス", e: "United Kingdom", c: "GB", r: "ヨーロッパ", p: 69138 },
  { n: "タンザニア", e: "Tanzania", c: "TZ", r: "アフリカ", p: 68560 },
  { n: "フランス", e: "France", c: "FR", r: "ヨーロッパ", p: 66549 },
  { n: "南アフリカ", e: "South Africa", c: "ZA", r: "アフリカ", p: 64007 },
  { n: "イタリア", e: "Italy", c: "IT", r: "ヨーロッパ", p: 59342 },
  { n: "ケニア", e: "Kenya", c: "KE", r: "アフリカ", p: 56433 },
  { n: "ミャンマー", e: "Myanmar", c: "MM", r: "アジア", p: 54500 },
  { n: "コロンビア", e: "Colombia", c: "CO", r: "南米", p: 52886 },
  { n: "韓国", e: "South Korea", c: "KR", r: "アジア", p: 51717 },
  { n: "スーダン", e: "Sudan", c: "SD", r: "アフリカ", p: 50448 },
  { n: "ウガンダ", e: "Uganda", c: "UG", r: "アフリカ", p: 50015 },
  { n: "スペイン", e: "Spain", c: "ES", r: "ヨーロッパ", p: 47911 },
  { n: "アルジェリア", e: "Algeria", c: "DZ", r: "アフリカ", p: 46815 },
  { n: "イラク", e: "Iraq", c: "IQ", r: "アジア", p: 46042 },
  { n: "アルゼンチン", e: "Argentina", c: "AR", r: "南米", p: 45696 },
  { n: "アフガニスタン", e: "Afghanistan", c: "AF", r: "アジア", p: 42647 },
  { n: "イエメン", e: "Yemen", c: "YE", r: "アジア", p: 40584 },
  { n: "カナダ", e: "Canada", c: "CA", r: "北米", p: 39742 },
  { n: "ポーランド", e: "Poland", c: "PL", r: "ヨーロッパ", p: 38539 },
  { n: "モロッコ", e: "Morocco", c: "MA", r: "アフリカ", p: 38081 },
  { n: "アンゴラ", e: "Angola", c: "AO", r: "アフリカ", p: 37886 },
  { n: "ウクライナ", e: "Ukraine", c: "UA", r: "ヨーロッパ", p: 37860 },
  { n: "ウズベキスタン", e: "Uzbekistan", c: "UZ", r: "アジア", p: 36361 },
  { n: "マレーシア", e: "Malaysia", c: "MY", r: "アジア", p: 35557 },
  { n: "モザンビーク", e: "Mozambique", c: "MZ", r: "アフリカ", p: 34631 },
  { n: "ガーナ", e: "Ghana", c: "GH", r: "アフリカ", p: 34428 },
  { n: "ペルー", e: "Peru", c: "PE", r: "南米", p: 34217 },
  { n: "サウジアラビア", e: "Saudi Arabia", c: "SA", r: "アジア", p: 33962 },
  { n: "マダガスカル", e: "Madagascar", c: "MG", r: "アフリカ", p: 31964 },
  { n: "コートジボワール", e: "Côte d'Ivoire", c: "CI", r: "アフリカ", p: 31165 },
  { n: "ネパール", e: "Nepal", c: "NP", r: "アジア", p: 29651 },
  { n: "カメルーン", e: "Cameroon", c: "CM", r: "アフリカ", p: 29123 },
  { n: "ベネズエラ", e: "Venezuela", c: "VE", r: "南米", p: 28406 },
  { n: "ニジェール", e: "Niger", c: "NE", r: "アフリカ", p: 27202 },
  { n: "オーストラリア", e: "Australia", c: "AU", r: "オセアニア", p: 26713 },
  { n: "北朝鮮", e: "North Korea", c: "KP", r: "アジア", p: 26498 },
  { n: "シリア", e: "Syria", c: "SY", r: "アジア", p: 24672 },
  { n: "マリ", e: "Mali", c: "ML", r: "アフリカ", p: 24479 },
  { n: "ブルキナファソ", e: "Burkina Faso", c: "BF", r: "アフリカ", p: 23548 },
  { n: "台湾", e: "Taiwan", c: "TW", r: "アジア", p: 23400 },
  { n: "スリランカ", e: "Sri Lanka", c: "LK", r: "アジア", p: 23103 },
  { n: "マラウイ", e: "Malawi", c: "MW", r: "アフリカ", p: 21656 },
  { n: "ザンビア", e: "Zambia", c: "ZM", r: "アフリカ", p: 21314 },
  { n: "カザフスタン", e: "Kazakhstan", c: "KZ", r: "アジア", p: 20593 },
  { n: "チャド", e: "Chad", c: "TD", r: "アフリカ", p: 20299 },
  { n: "チリ", e: "Chile", c: "CL", r: "南米", p: 19764 },
  { n: "ルーマニア", e: "Romania", c: "RO", r: "ヨーロッパ", p: 19015 },
  { n: "ソマリア", e: "Somalia", c: "SO", r: "アフリカ", p: 19010 },
  { n: "セネガル", e: "Senegal", c: "SN", r: "アフリカ", p: 18502 },
  { n: "グアテマラ", e: "Guatemala", c: "GT", r: "北米", p: 18406 },
  { n: "オランダ", e: "Netherlands", c: "NL", r: "ヨーロッパ", p: 18228 },
  { n: "エクアドル", e: "Ecuador", c: "EC", r: "南米", p: 18135 },
  { n: "カンボジア", e: "Cambodia", c: "KH", r: "アジア", p: 17638 },
  { n: "ジンバブエ", e: "Zimbabwe", c: "ZW", r: "アフリカ", p: 16635 },
  { n: "ギニア", e: "Guinea", c: "GN", r: "アフリカ", p: 14755 },
  { n: "ベナン", e: "Benin", c: "BJ", r: "アフリカ", p: 14462 },
  { n: "ルワンダ", e: "Rwanda", c: "RW", r: "アフリカ", p: 14257 },
  { n: "ブルンジ", e: "Burundi", c: "BI", r: "アフリカ", p: 14047 },
  { n: "ボリビア", e: "Bolivia", c: "BO", r: "南米", p: 12414 },
  { n: "チュニジア", e: "Tunisia", c: "TN", r: "アフリカ", p: 12277 },
  { n: "南スーダン", e: "South Sudan", c: "SS", r: "アフリカ", p: 11944 },
  { n: "ハイチ", e: "Haiti", c: "HT", r: "北米", p: 11772 },
  { n: "ベルギー", e: "Belgium", c: "BE", r: "ヨーロッパ", p: 11738 },
  { n: "ヨルダン", e: "Jordan", c: "JO", r: "アジア", p: 11553 },
  { n: "ドミニカ共和国", e: "Dominican Republic", c: "DO", r: "北米", p: 11428 },
  { n: "アラブ首長国連邦", e: "United Arab Emirates", c: "AE", r: "アジア", p: 11027 },
  { n: "キューバ", e: "Cuba", c: "CU", r: "北米", p: 10979 },
  { n: "チェコ", e: "Czechia", c: "CZ", r: "ヨーロッパ", p: 10874 },
  { n: "ホンジュラス", e: "Honduras", c: "HN", r: "北米", p: 10826 },
  { n: "パプアニューギニア", e: "Papua New Guinea", c: "PG", r: "オセアニア", p: 10577 },
  { n: "タジキスタン", e: "Tajikistan", c: "TJ", r: "アジア", p: 10590 },
  { n: "スウェーデン", e: "Sweden", c: "SE", r: "ヨーロッパ", p: 10606 },
  { n: "ポルトガル", e: "Portugal", c: "PT", r: "ヨーロッパ", p: 10426 },
  { n: "アゼルバイジャン", e: "Azerbaijan", c: "AZ", r: "アジア", p: 10336 },
  { n: "ギリシャ", e: "Greece", c: "GR", r: "ヨーロッパ", p: 10047 },
  { n: "ハンガリー", e: "Hungary", c: "HU", r: "ヨーロッパ", p: 9676 },
  { n: "トーゴ", e: "Togo", c: "TG", r: "アフリカ", p: 9515 },
  { n: "イスラエル", e: "Israel", c: "IL", r: "アジア", p: 9388 },
  { n: "オーストリア", e: "Austria", c: "AT", r: "ヨーロッパ", p: 9120 },
  { n: "ベラルーシ", e: "Belarus", c: "BY", r: "ヨーロッパ", p: 9020 },
  { n: "スイス", e: "Switzerland", c: "CH", r: "ヨーロッパ", p: 8922 },
  { n: "シエラレオネ", e: "Sierra Leone", c: "SL", r: "アフリカ", p: 8642 },
  { n: "ラオス", e: "Laos", c: "LA", r: "アジア", p: 7770 },
  { n: "トルクメニスタン", e: "Turkmenistan", c: "TM", r: "アジア", p: 7494 },
  { n: "香港", e: "Hong Kong", c: "HK", r: "アジア", p: 7415 },
  { n: "リビア", e: "Libya", c: "LY", r: "アフリカ", p: 7381 },
  { n: "キルギス", e: "Kyrgyzstan", c: "KG", r: "アジア", p: 7186 },
  { n: "ニカラグア", e: "Nicaragua", c: "NI", r: "北米", p: 7046 },
  { n: "パラグアイ", e: "Paraguay", c: "PY", r: "南米", p: 6929 },
  { n: "セルビア", e: "Serbia", c: "RS", r: "ヨーロッパ", p: 6736 },
  { n: "ブルガリア", e: "Bulgaria", c: "BG", r: "ヨーロッパ", p: 6714 },
  { n: "エルサルバドル", e: "El Salvador", c: "SV", r: "北米", p: 6338 },
  { n: "コンゴ共和国", e: "Republic of the Congo", c: "CG", r: "アフリカ", p: 6333 },
  { n: "デンマーク", e: "Denmark", c: "DK", r: "ヨーロッパ", p: 5977 },
  { n: "レバノン", e: "Lebanon", c: "LB", r: "アジア", p: 5806 },
  { n: "シンガポール", e: "Singapore", c: "SG", r: "アジア", p: 5832 },
  { n: "フィンランド", e: "Finland", c: "FI", r: "ヨーロッパ", p: 5617 },
  { n: "リベリア", e: "Liberia", c: "LR", r: "アフリカ", p: 5613 },
  { n: "ノルウェー", e: "Norway", c: "NO", r: "ヨーロッパ", p: 5576 },
  { n: "パレスチナ", e: "Palestine", c: "PS", r: "アジア", p: 5495 },
  { n: "スロバキア", e: "Slovakia", c: "SK", r: "ヨーロッパ", p: 5474 },
  { n: "中央アフリカ共和国", e: "Central African Republic", c: "CF", r: "アフリカ", p: 5330 },
  { n: "オマーン", e: "Oman", c: "OM", r: "アジア", p: 5281 },
  { n: "アイルランド", e: "Ireland", c: "IE", r: "ヨーロッパ", p: 5255 },
  { n: "ニュージーランド", e: "New Zealand", c: "NZ", r: "オセアニア", p: 5213 },
  { n: "モーリタニア", e: "Mauritania", c: "MR", r: "アフリカ", p: 5169 },
  { n: "コスタリカ", e: "Costa Rica", c: "CR", r: "北米", p: 5106 },
  { n: "クウェート", e: "Kuwait", c: "KW", r: "アジア", p: 4934 },
  { n: "パナマ", e: "Panama", c: "PA", r: "北米", p: 4515 },
  { n: "クロアチア", e: "Croatia", c: "HR", r: "ヨーロッパ", p: 3875 },
  { n: "ジョージア", e: "Georgia", c: "GE", r: "アジア", p: 3807 },
  { n: "エリトリア", e: "Eritrea", c: "ER", r: "アフリカ", p: 3535 },
  { n: "モンゴル", e: "Mongolia", c: "MN", r: "アジア", p: 3504 },
  { n: "ウルグアイ", e: "Uruguay", c: "UY", r: "南米", p: 3386 },
  { n: "プエルトリコ", e: "Puerto Rico", c: "PR", r: "北米", p: 3204 },
  { n: "ボスニア・ヘルツェゴビナ", e: "Bosnia and Herzegovina", c: "BA", r: "ヨーロッパ", p: 3164 },
  { n: "カタール", e: "Qatar", c: "QA", r: "アジア", p: 3048 },
  { n: "モルドバ", e: "Moldova", c: "MD", r: "ヨーロッパ", p: 3034 },
  { n: "ナミビア", e: "Namibia", c: "NA", r: "アフリカ", p: 3030 },
  { n: "アルメニア", e: "Armenia", c: "AM", r: "アジア", p: 2973 },
  { n: "リトアニア", e: "Lithuania", c: "LT", r: "ヨーロッパ", p: 2859 },
  { n: "ジャマイカ", e: "Jamaica", c: "JM", r: "北米", p: 2839 },
  { n: "アルバニア", e: "Albania", c: "AL", r: "ヨーロッパ", p: 2777 },
  { n: "ガンビア", e: "Gambia", c: "GM", r: "アフリカ", p: 2759 },
  { n: "ガボン", e: "Gabon", c: "GA", r: "アフリカ", p: 2538 },
  { n: "ボツワナ", e: "Botswana", c: "BW", r: "アフリカ", p: 2521 },
  { n: "レソト", e: "Lesotho", c: "LS", r: "アフリカ", p: 2337 },
  { n: "ギニアビサウ", e: "Guinea-Bissau", c: "GW", r: "アフリカ", p: 2201 },
  { n: "スロベニア", e: "Slovenia", c: "SI", r: "ヨーロッパ", p: 2118 },
  { n: "赤道ギニア", e: "Equatorial Guinea", c: "GQ", r: "アフリカ", p: 1892 },
  { n: "ラトビア", e: "Latvia", c: "LV", r: "ヨーロッパ", p: 1871 },
  { n: "北マケドニア", e: "North Macedonia", c: "MK", r: "ヨーロッパ", p: 1823 },
  { n: "バーレーン", e: "Bahrain", c: "BH", r: "アジア", p: 1607 },
  { n: "コソボ", e: "Kosovo", c: "XK", r: "ヨーロッパ", p: 1591 },
  { n: "トリニダード・トバゴ", e: "Trinidad and Tobago", c: "TT", r: "北米", p: 1507 },
  { n: "東ティモール", e: "Timor-Leste", c: "TL", r: "アジア", p: 1400 },
  { n: "エストニア", e: "Estonia", c: "EE", r: "ヨーロッパ", p: 1360 },
  { n: "キプロス", e: "Cyprus", c: "CY", r: "ヨーロッパ", p: 1358 },
  { n: "モーリシャス", e: "Mauritius", c: "MU", r: "アフリカ", p: 1272 },
  { n: "エスワティニ", e: "Eswatini", c: "SZ", r: "アフリカ", p: 1242 },
  { n: "ジブチ", e: "Djibouti", c: "DJ", r: "アフリカ", p: 1168 },
  { n: "フィジー", e: "Fiji", c: "FJ", r: "オセアニア", p: 928 },
  { n: "コモロ", e: "Comoros", c: "KM", r: "アフリカ", p: 866 },
  { n: "ガイアナ", e: "Guyana", c: "GY", r: "南米", p: 831 },
  { n: "ソロモン諸島", e: "Solomon Islands", c: "SB", r: "オセアニア", p: 819 },
  { n: "ブータン", e: "Bhutan", c: "BT", r: "アジア", p: 791 },
  { n: "マカオ", e: "Macao", c: "MO", r: "アジア", p: 720 },
  { n: "ルクセンブルク", e: "Luxembourg", c: "LU", r: "ヨーロッパ", p: 673 },
  { n: "スリナム", e: "Suriname", c: "SR", r: "南米", p: 634 },
  { n: "モンテネグロ", e: "Montenegro", c: "ME", r: "ヨーロッパ", p: 632 },
  { n: "西サハラ", e: "Western Sahara", c: "EH", r: "アフリカ", p: 600 },
  { n: "マルタ", e: "Malta", c: "MT", r: "ヨーロッパ", p: 545 },
  { n: "モルディブ", e: "Maldives", c: "MV", r: "アジア", p: 528 },
  { n: "カーボベルデ", e: "Cabo Verde", c: "CV", r: "アフリカ", p: 525 },
  { n: "ブルネイ", e: "Brunei", c: "BN", r: "アジア", p: 462 },
  { n: "ベリーズ", e: "Belize", c: "BZ", r: "北米", p: 417 },
  { n: "バハマ", e: "Bahamas", c: "BS", r: "北米", p: 401 },
  { n: "アイスランド", e: "Iceland", c: "IS", r: "ヨーロッパ", p: 393 },
  { n: "バヌアツ", e: "Vanuatu", c: "VU", r: "オセアニア", p: 335 },
  { n: "バルバドス", e: "Barbados", c: "BB", r: "北米", p: 282 },
  { n: "サントメ・プリンシペ", e: "Sao Tome and Principe", c: "ST", r: "アフリカ", p: 235 },
  { n: "サモア", e: "Samoa", c: "WS", r: "オセアニア", p: 218 },
  { n: "セントルシア", e: "Saint Lucia", c: "LC", r: "北米", p: 179 },
  { n: "キリバス", e: "Kiribati", c: "KI", r: "オセアニア", p: 134 },
  { n: "セーシェル", e: "Seychelles", c: "SC", r: "アフリカ", p: 131 },
  { n: "グレナダ", e: "Grenada", c: "GD", r: "北米", p: 117 },
  { n: "ミクロネシア連邦", e: "Micronesia", c: "FM", r: "オセアニア", p: 115 },
  { n: "トンガ", e: "Tonga", c: "TO", r: "オセアニア", p: 105 },
  { n: "セントビンセント・グレナディーン", e: "St. Vincent & Grenadines", c: "VC", r: "北米", p: 100 },
  { n: "アンティグア・バーブーダ", e: "Antigua and Barbuda", c: "AG", r: "北米", p: 93 },
  { n: "アンドラ", e: "Andorra", c: "AD", r: "ヨーロッパ", p: 82 },
  { n: "ドミニカ国", e: "Dominica", c: "DM", r: "北米", p: 66 },
  { n: "リヒテンシュタイン", e: "Liechtenstein", c: "LI", r: "ヨーロッパ", p: 40 },
  { n: "モナコ", e: "Monaco", c: "MC", r: "ヨーロッパ", p: 38 },
  { n: "マーシャル諸島", e: "Marshall Islands", c: "MH", r: "オセアニア", p: 37 },
  { n: "サンマリノ", e: "San Marino", c: "SM", r: "ヨーロッパ", p: 33 },
  { n: "パラオ", e: "Palau", c: "PW", r: "オセアニア", p: 18 },
  { n: "ナウル", e: "Nauru", c: "NR", r: "オセアニア", p: 12 },
  { n: "ツバル", e: "Tuvalu", c: "TV", r: "オセアニア", p: 10 },
  { n: "バチカン市国", e: "Vatican City", c: "VA", r: "ヨーロッパ", p: 1 },
];

